### ISSUE TITLE
An italics version

### ISSUE THREAD

**Issue by tommarien** [hedinne/popping-and-locking-vscode#10]
Hi, I am using your theme for months now and I really love it but I was wondering could you create an italics keyword version ?

Thanks

**Comment by hedinne** [comment]
Hi. I'm really happy you like it. I originally wrote this theme with italics but I removed them at some point. If I remember correctly there was some problem with them and I didn't want to force people to use them. Rather just let people add the code to their own settings.json. I am (slowly) working on a rewrite and I could maybe write it in a way that I could I apply italics to a fork of the main version. But I don't know when I will be able to finish that.

**Comment by tommarien** [comment]
@hedinne Would be great, let me know if i can help in someway ;)
