### ISSUE TITLE
Support bracket pair colorization

### ISSUE THREAD

**Issue by jsejcksn** [hedinne/popping-and-locking-vscode#12]
VS Code v1.60 has been released, and there is now [native support for bracket pair colorization](https://code.visualstudio.com/updates/v1_60#_high-performance-bracket-pair-colorization) (a separate extension is no longer needed). This theme can include [the colors specified in the readme](https://github.com/hedinne/popping-and-locking-vscode/issues/9) in order to support the new feature.

**Comment by hedinne** [comment]
Sure, I was just about to publish it. Until then, here is the code if you (or someone else) want to add it to their settings.
 ```json
  "workbench.colorCustomizations": {
    "editorBracketHighlight.foreground1": "#cc241d",
    "editorBracketHighlight.foreground2": "#b16286",
    "editorBracketHighlight.foreground3": "#458588",
    "editorBracketHighlight.foreground4": "#689d6a",
    "editorBracketHighlight.foreground5": "#98971a",
    "editorBracketHighlight.foreground6": "#d79921",
    "editorBracketHighlight.unexpectedBracket.foreground": "#ffffff"
  },
  ```

**Comment by hedinne** [comment]
Done.
