### ISSUE TITLE
Which font are you using?

### ISSUE THREAD

**Issue by mittalyashu** [hedinne/popping-and-locking-vscode#2]
Which font is used in these examples?

![image](https://user-images.githubusercontent.com/29014463/45027005-cf3b0980-b05d-11e8-9c62-c1a3ba9d4066.png)

![image](https://user-images.githubusercontent.com/29014463/45027008-d06c3680-b05d-11e8-9594-cc3a6bb269e5.png)

**Comment by hedinne** [comment]
I'm using [Operator Mono SSm Lig](https://github.com/kiliman/operator-mono-lig) in these examples. It just regular Operator Mono SSm with added ligatures.

And If your are thinking of changing fonts, I would checkout [Dank Mono](https://dank.sh/). I'm a big fan of that font.

**Comment by mittalyashu** [comment]
What about the theme 😋?

**Comment by hedinne** [comment]
I use this theme (popping-and-locking) 😉

**Comment by mittalyashu** [comment]
@hedinne I have installed your theme, and when I enabled your theme, it was so bright that I had to literally close my eyes 🙈.

![image](https://user-images.githubusercontent.com/29014463/45313922-db3b3580-b54d-11e8-92d6-aaf1fe130008.png)

**Comment by hedinne** [comment]
I really can't speak to it being bright since it is dark blue. The reason it looks different on your computer is that you have "High contrast" turned on in Window settings.
