### ISSUE TITLE
tell me which font u used in this theme,plz

### ISSUE THREAD

**Issue by rosejcs** [hedinne/popping-and-locking-vscode#3]
hello,which font do u use in this theme's screenshots

**Comment by hedinne** [comment]
I'm using [Operator Mono SSm Lig](https://github.com/kiliman/operator-mono-lig) in these examples. It just regular Operator Mono SSm with added ligatures.

And If your are thinking of changing fonts, you might wan't to checkout [Dank Mono](https://dank.sh/). I'm a big fan of that font.

**Comment by rosejcs** [comment]
thanks,its helpfull!

At 2019-01-03 22:09:57, "Hedinn Eiriksson" <notifications@github.com> wrote:


I'm using Operator Mono SSm Lig in these examples. It just regular Operator Mono SSm with added ligatures.

And If your are thinking of changing fonts, you might wan't to checkout Dank Mono. I'm a big fan of that font.

**Comment by rosejcs** [comment]
thanks!:)
