### ISSUE TITLE
what is the licence 

### ISSUE THREAD

**Issue by Luxcium** [hedinne/popping-and-locking-vscode#4]
What is the licence used for this repository ? 
Can I republish a modified version on the VS Code market place or is it better to do a pull request of my changes for a review and possible aprobation ?

**Comment by hedinne** [comment]
I totally forgot to add a licence. I haven't decided what kind of licence to use but it will probably be WTFPL, MIT or something similar. So in short, you can do what ever you want with the code.

I also welcome PRs. What do you want to modify? If it's a major change then we could maybe publish it as an alternate version. I've been planning a rewrite to fix some consistency problems. But the last few months have been very hectic and I haven't gotten around to it.

**Comment by Luxcium** [comment]
I am new to working on repos but more new working with themes... 

I think this is a smaller project so it may be easy for me to add my grain of salt if its ok to do so ... 

First of all I dont know what is the best way to communicate about the project with you here is nice because its public but maybe it is not the right place since my question are a mix of personal/private question and some are not directly related to this specific project maybe ...

First of all I dont know how to use my local cloned copy instead of the one I dowloaded from market place to be able to make small edits to the theme for my personal use ...

then I would like to propose those small changes to maybe get included in this official project ... 

I know more than a newbie but less than an experienced git hub maintainer etc ..

**Comment by Luxcium** [comment]
Finally, it seems that I have passed half of all hours in my life over the last few weeks working on that theme. I think I will go with my own version. When I say I think I mean that its a decision already made. Tanks a lot because without your work, as a basis to my inspiration, I would be able to have a theme as nice as it is today. I am proud of my colours and hope I will not be the only one to think the [Pop N' Lock Theme by Luxcium](https://marketplace.visualstudio.com/items?itemName=Luxcium.pop-n-lock-theme-vscode) theme is the most beautiful in the market place...
It is not perfect and I still am tweaking stuff but it really has been a long process for me and nobody will be able to understand how much effort it took me to get that result (even me I do not understand how I managed to put so many hours tweaking each red, green, blue or alpha component of each TS token or workbench colour customizations) ... 

I wish you a nice day @hedinne I will always be grateful for what you did for my theme it is the reason why I have based my name on your theme's name so everyone will know where it comes from.

**Comment by Luxcium** [comment]
I also have used the same JavaScript code I saw on your screenshots to be able to compare adequately in both JS and TS let me know what you think:

[![Luxcium POP N LOCK THEME Image](https://raw.githubusercontent.com/luxcium/pop-n-lock-theme-vscode/master/images/v3.7.0/JS2.png)](https://raw.githubusercontent.com/luxcium/pop-n-lock-theme-vscode/master/images/v3.7.0/JS1.png) 

[![hedinne Image](https://raw.githubusercontent.com/hedinne/popping-and-locking-vscode/master/images/js.png)](https://raw.githubusercontent.com/hedinne/popping-and-locking-vscode/master/images/js.png) 

[![Luxcium POP N LOCK THEME Image](https://raw.githubusercontent.com/luxcium/pop-n-lock-theme-vscode/master/images/v3.7.0/TS2.png)](https://raw.githubusercontent.com/luxcium/pop-n-lock-theme-vscode/master/images/v3.7.0/TS1.png)
