### ISSUE TITLE
python custom defined func highlight failure

### ISSUE THREAD

**Issue by cerebrumaize** [hedinne/popping-and-locking-vscode#6]
Python function defined by myself has the same color with plain text. Is it possible to recognize customize function for python specifically?

**Comment by hedinne** [comment]
Sorry I haven't replied. I was always going to check out python with this extension but never got around to it.

I'm working on a rewrite that should target element more broadly and work better with languages that I don't design for.

After the rewrite, If there are some fixes to python I should do. Please let me know.
