### ISSUE TITLE
Settings for Bracket Pair Colorizer 2

### ISSUE THREAD

**Issue by jsejcksn** [hedinne/popping-and-locking-vscode#9]
Is this correct?

```json
{
  "bracket-pair-colorizer-2.colors": [
    "#cc241d",
    "#b16286",
    "#458588",
    "#689d6a",
    "#98971a",
    "#d79921"
  ],
  "bracket-pair-colorizer-2.unmatchedScopeColor": "#f2e5bc"
}
```

If not, will you please correct and add to the documentation? Thanks!

**Comment by hedinne** [comment]
I'll check and update it next week.

**Comment by jsejcksn** [comment]
@hedinne Did you ever take a look at this?

**Comment by hedinne** [comment]
Hey hey, sorry for the late replay. Yes, I added it to the readme and published just now. Thank you for the contribution.
